### ISSUE TITLE
Runtime for user-defined actor and testing harness

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc-subnet-actor#1]
The subnet actor is not as rigorous as the the SCA actor was in terms of where messages can be sent. In the SCA, the actor calls the state for mutation, then sends the message. This time both the state and and the actor can send messages. Plus there are flags for testing, and during testing messages aren't sent but accumulated, like a mock object (which is horrible). This is a consequence of not having a testing harness nor a runtime to seamlessly write unit tests.

Let's see where the FVM Rust SDK gets, but if in a few months there's nothing usable that fits our needs we should consider adopting some variation of @aakoshh interface proposal from below (maybe with a mutable reference like the SCA does with the runtime) so the reference implementation resembles more of the good practice the SCA seems to do, but supported by the type system, rather than just conventions. 

> @aakoshh To model "pure" consensus state I tried to capture it with this [finite state machine](https://github.com/aakoshh/rust-consensus-exp/blob/master/src/paxos/first/fsm.rs#L15-L27) interface [implemented](https://github.com/aakoshh/rust-consensus-exp/blob/master/src/paxos/first/mod.rs) for the consensus, which is similar in spirit to the SCA, but it allows the state transition logic to return some actions/effects it wants to happen, such as [broadcasting messages](https://github.com/aakoshh/rust-consensus-exp/blob/master/src/paxos/mod.rs#L110-L113), without actually being able to even attempt to do it on its own. The effects are then carried out by the [actor equivalent](https://github.com/aakoshh/rust-consensus-exp/blob/master/src/paxos/third/mod.rs). I makes the core logic nicely testable as it has no side effects.

**Comment by cryptoAtwill** [comment]
To break this further down, here is a summary of what we discussed:
1. Migrate `runtime` and `mocked runtime` and other relevant crates from `builtin-actors` to `fvm-utils`.
2. Create a simple fvm user actor that uses the `fvm-utils`
3. Compile and deploy to wasm
@adlrocha please help check it out and feel free to add missing steps.

**Comment by sergefdrv** [comment]
Are we going to upgrade to the latest `ref-fvm` first? Any use of the FVM Rust SDK?

**Comment by cryptoAtwill** [comment]
@sergefdrv my understanding is we will not relying on `ref-fvm` for this one, at least for the unit testing part.

**Comment by adlrocha** [comment]
> Are we going to upgrade to the latest ref-fvm first? Any use of the FVM Rust SDK?

If we end up using `ref-fvm` for anything we should point to the latest version in master.

> @sergefdrv my understanding is we will not relying on ref-fvm for this one, at least for the unit testing part.

But that being said, as @cryptoAtwill mentions, the expectation is that we will completely remove all our dependencies from `ref-fvm` (apart from the low-level `sdk`), and we will start using our runtime abstraction. Even the `hierarchical addresses` that we implemented in our fork of `ref-fvm` will be replaced by a compatible `f4 address` ([see for context](https://github.com/filecoin-project/FIPs/discussions/473)). That will mean porting this actor to use our runtime abstraction as the issue suggest.

**Comment by sergefdrv** [comment]
I see that we're about to stop using `ref-fvm`. I was just wondering if we can rely on [FVM SDK](https://github.com/polyphene/fvm-rs-sdk) in our runtime abstraction.

**Comment by adlrocha** [comment]
Sure, we can use the Rust SDK, and get inspiration from it. My only concern is that this was a grant and it's been 3 months since the last update. I don't know if it is still actively maintained. We should maybe ask if we see that we need it.

**Comment by sergefdrv** [comment]
I think we could either find it useful and take advantage of the existing code or implement something ourselves. In any case we might need to do some maintenance.
